title: raisercostin's blog
author: costin grigore
#url: 'http://raisercostin.org'
email: raisercostin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Raisercostin's blog with half baked 
  thoughts, ideas, mindmaps, projects.

# Build settings
markdown: kramdown
#@see https://github.com/jekyll/minima
theme: minima
#theme: jekyll-theme-minimal
gems:
  #see https://github.com/jekyll/jekyll-feed
  - jekyll-feed
  - jekyll-seo-tag
  #see https://github.com/jekyll/jekyll-archives
  - jekyll-archives

#minima theme config vars  
google_analytics: ["UA-45773408-2"]

exclude:
  - Gemfile
  - Gemfile.lock
  - "**/*.mm"

disqus:
    shortname: raisercostin

permalink: /:year/:month/:day/:title

excerpt_separator: "{{ more }}"

collections: 
    favicons:
        output: true
        permalink: /:path/
    images:
        output: true
        permalink: /:path/
    binaries:
        output: true
        permalink: /binaries/:path/
    feeds:
        output: true
        permalink: /:path
    images:
        output: true
        permalink: /:path/

paginate: 10
paginate_path: '/blog/page:num/'
repository: raisercostin/raisercostin.github.io.git

footer-links:
  dribbble:
  email: raisercostin@gmail.com
  facebook: raisercostin
  flickr:
  github: raisercostin
  instagram: raisercostin
  linkedin: raisercostin
  pinterest:
  rss: atom.xml # feed.xml is the default one generated by jekyll-feed. Valid according to http://validator.w3.org/feed/check.cgi?url=http://raisercostin.org/feed.xml . You could also use /rss2.xml /atom.xml
  twitter: raisercostin
  stackoverflow: users/99248/raisercostin # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube:  # channel/<your_long_string> or user/<user-name>
  googleplus: +raisercostingrigore # anything in your profile username that comes after plus.google.com/
  goodreads: raisercostin

#default variables for posts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      imageStyle: "width:100%"