title: raisercostin's blog
author: costin grigore
#url: 'http://raisercostin.org'
email: raisercostin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Raisercostin's blog with half baked 
  thoughts, ideas, mindmaps, projects.

twitter_username: raisercostin
github_username:  raisercostin

# Build settings
markdown: kramdown
#@see https://github.com/jekyll/minima
theme: minima
#theme: jekyll-theme-minimal
gems:
  #see https://github.com/jekyll/jekyll-feed
  - jekyll-feed
  - jekyll-seo-tag
  #see https://github.com/jekyll/jekyll-archives
  - jekyll-archives

#minima theme config vars  
google_analytics: ["UA-45773408-2"]
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
    shortname: raisercostin

permalink: /:year/:month/:day/:title

excerpt_separator: "<!-- more -->"
